language: node_js

node_js:
  - "0.10"

before_script:
  - "mkdir ~/.npm"
  - npm install gulp
  - ./scripts/travis/wait_for_browser_provider.sh

script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - ./scripts/travis/build.sh

notifications:
  email:
    - kmsh3ng@gmail.com

  slack:
    rooms:
      - sys:yeTvjm0bw1tX6MBWrfkVL5RG#travis
