language: node_js

node_js:
  - "0.10"

before_script:
  - npm install gulp
  - ./scripts/travis/wait_for_browser_provider.sh

script:
  - ./scripts/travis/build.sh

notifications:
  email:
    - kmsh3ng@gmail.com
